---
#########################
#########################
## Deploy Docker Image Flavors ##
#########################
#########################

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#######################################
# Start the job on all push to main #
#######################################
name: "Build & Deploy - BETA Flavors"
on:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/**"
      - "Dockerfile"
      - "flavors/**"
      - "megalinter/**"
      - "mega-linter-runner/**"
      - "**/linter-versions.json"
      - "TEMPLATES/**"
      - ".trivyignore"
      - "**/.sh"

###############
# Set the Job #
###############
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    # Name the Job
    name: BETA/Flavors
    # Set the agent to run on
    runs-on: ubuntu-latest
    permissions:
      actions: write
      packages: write
    environment:
      name: beta
    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        # flavors-start
        flavor:
          [
            "bioinformatics",
          ]
# flavors-end
        platform: ["linux/amd64"]
    # Only run this on the main repo
    if: >-
      (
        github.repository == 'uclahs-cds/megalinter'
        && !contains(github.event.head_commit.message, 'skip deploy')
        && !contains(github.event.head_commit.message, 'Release MegaLinter v')
      )
    ##################
    # Load all steps #
    ##################
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Docker Metadata action
        uses: docker/metadata-action@v5.5.1
        id: meta
        with:
          images: |
            ghcr.io/${{ github.repository }}-${{ matrix.flavor }}
          flavor: |
            latest=false
            prefix=beta
          tags: |
            type=raw,value=

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        if: ${{ ( ( runner.arch != 'X64' || runner.os != 'Linux' ) && matrix.platform == 'linux/amd64' ) || matrix.platform != 'linux/amd64' }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Free disk space
      - name: Free Disk space
        shell: bash
        run: |
          sudo rm -rf /usr/local/lib/android  # will release about 10 GB if you don't need Android
          sudo rm -rf /usr/share/dotnet # will release about 20GB if you don't need .NET

      - name: Build Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: flavors/${{ matrix.flavor }}/Dockerfile
          platforms: ${{ matrix.platform }}
          build-args: |
            BUILD_DATE=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.created'] }}
            BUILD_VERSION=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
            BUILD_REVISION=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.revision'] }}
          load: false
          push: ${{ github.event_name != 'pull_request' }}
          secrets: |
            GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          tags: ${{ steps.meta.outputs.tags }}
